language: node_js
node_js: "8"
script:
  - npm run lint
  - npm run build
  - npm test
branches:
  only:
  - master
cache:
  directories:
    - node_modules
before_install:
  - mysql -e 'CREATE DATABASE testdb;'
